DECLARE    
    EXEC SQL 
        DECLARE ESTUDCUR CURSOR FOR
        SELECT ESTUDANTE-ID, ESTUDANTE-NOME, ESTUDANTE-ENDERECO FROM ESTUDANTE
        WHERE ESTUDANTE-ID > :WS-ESTUDANTE-ID
    END-EXEC.

OPEN
    EXEC SQL
        OPEN ESTUDCUR
    END-EXEC.

FETCH
    EXEC SQL
        FETCH ESTUDCUR
        INTO :WS-ESTUDANTE-ID, :WS-ESTUDANTE-NOME, :WS-ESTUDANTE-ENDERECO
    END-EXEC.